In [1]:
list_2d = [[1,2,3],
           [4,5,6]]
print(list_2d[0])
print(list_2d[1][2])

6


In [4]:
data_kunjungan = {
    'Senin'  : {'PAI' : 4,  'GF' : 5,  'K' : 6},
    'Selasa' : {'PAI' : 10, 'GF' : 20, 'K' : 50}
}
#print(data_kunjungan['Senin'])
#print(data_kunjungan['Senin']['K'])

for hari,total in data_kunjungan.items():
    print(f"Hari: {hari} {total}")

{'PAI': 4, 'GF': 5, 'K': 6}
6
Hari: Senin {'PAI': 4, 'GF': 5, 'K': 6}
Hari: Selasa {'PAI': 10, 'GF': 20, 'K': 50}


In [13]:
import numpy as np

array_2d_numpy = np.array([
    [3,4,5],
    [6,10,60],
    [20,40,40]
    ])

print(array_2d_numpy[2,1])
jumlah_baris = np.sum(array_2d_numpy, axis=0)
jumlah_kolom = np.sum(array_2d_numpy, axis=1)
print(jumlah_baris)
print(jumlah_kolom)

# Melihat Index Tertinggi Tiap Baris
nilai_max_baris = np.argmax(array_2d_numpy, axis=0)
print(nilai_max_baris)

# Melihat Nilai Tertinggi Tiap Baris
nilai_max_baris_val = np.max(array_2d_numpy, axis=1)
print(nilai_max_baris_val)

# Melihat Index Tertinggi Tiap Kolom
nilai_max_kolom = np.argmax(array_2d_numpy, axis=1)
print(nilai_max_kolom)

# Melihat Nilai Tertinggi Tiap Kolom
nilai_max_kolom_val = np.max(array_2d_numpy, axis=0)
print(nilai_max_kolom_val)

40
[ 29  54 105]
[ 12  76 100]
[2 2 1]
[ 5 60 40]
[2 2 1]
[20 40 60]


In [18]:
import pandas as bear

data = {
    'senin' : [1,4,5],
    'selasa' : [3,6,7],
}
df2 = bear.DataFrame(data, index=['laptop','hp','printer'])
print(df2,'\n')

# ubah dictionary jadi dataframe
data_kunjungan = {
    'Senin'  : {'PAI' : 4,  'GF' : 5,  'K' : 6},
    'Selasa' : {'PAI' : 10, 'GF' : 20, 'K' : 50}
}
print(bear.DataFrame(data_kunjungan),'\n')

array_2d = [
    [1,3,4],
    [1,6,7],
    [1,6,7],
]
# ubah array jadi dataframe
df1 = bear.DataFrame(array_2d, index=['laptop','hp','printer'], columns=['senin','selasa','rabu'])

print(df1,'\n')

total_nilai_tiap_baris = df1.sum(axis=0)
total_nilai_tiap_kolom = df1.sum(axis=1)
print(total_nilai_tiap_baris,'\n')
print(total_nilai_tiap_kolom)

         senin  selasa
laptop       1       3
hp           4       6
printer      5       7 

     Senin  Selasa
PAI      4      10
GF       5      20
K        6      50 

         senin  selasa  rabu
laptop       1       3     4
hp           1       6     7
printer      1       6     7 

senin      3
selasa    15
rabu      18
dtype: int64 

laptop      8
hp         14
printer    14
dtype: int64
